### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by aivanzipper** [1Strategy/blog-aws-extend-switch-roles#1]
After AWS Console upgrade at weekend 19-20 Sep 2020, extension doesn't work: it doesn't appear in switchrole dropdown menu. Checked in Chrome and Firefox.

**Comment by techotron** [comment]
@aivanzipper  - I've found the same issue. Did you close this because you found a resolution? Could you please share it?

**Comment by aivanzipper** [comment]
> @aivanzipper - I've found the same issue. Did you close this because you found a resolution? Could you please share it?

I closed this as it was the wrong repo.
I use https://github.com/tilfin/aws-extend-switch-roles
